// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0
// source: api/proto/friend.proto

package friendpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NameDisplayType int32

const (
	NameDisplayType_FIRST_NAME_FIRST NameDisplayType = 0
	NameDisplayType_LAST_NAME_FIRST  NameDisplayType = 1
)

// Enum value maps for NameDisplayType.
var (
	NameDisplayType_name = map[int32]string{
		0: "FIRST_NAME_FIRST",
		1: "LAST_NAME_FIRST",
	}
	NameDisplayType_value = map[string]int32{
		"FIRST_NAME_FIRST": 0,
		"LAST_NAME_FIRST":  1,
	}
)

func (x NameDisplayType) Enum() *NameDisplayType {
	p := new(NameDisplayType)
	*p = x
	return p
}

func (x NameDisplayType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NameDisplayType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_friend_proto_enumTypes[0].Descriptor()
}

func (NameDisplayType) Type() protoreflect.EnumType {
	return &file_api_proto_friend_proto_enumTypes[0]
}

func (x NameDisplayType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NameDisplayType.Descriptor instead.
func (NameDisplayType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_friend_proto_rawDescGZIP(), []int{0}
}

type BasicFriendData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId       string `protobuf:"bytes,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	FirstName       string `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName        string `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	NameDisplayType string `protobuf:"bytes,4,opt,name=nameDisplayType,proto3" json:"nameDisplayType,omitempty"`
	AvatarURL       string `protobuf:"bytes,5,opt,name=avatarURL,proto3" json:"avatarURL,omitempty"`
}

func (x *BasicFriendData) Reset() {
	*x = BasicFriendData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_friend_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BasicFriendData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicFriendData) ProtoMessage() {}

func (x *BasicFriendData) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_friend_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicFriendData.ProtoReflect.Descriptor instead.
func (*BasicFriendData) Descriptor() ([]byte, []int) {
	return file_api_proto_friend_proto_rawDescGZIP(), []int{0}
}

func (x *BasicFriendData) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *BasicFriendData) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *BasicFriendData) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *BasicFriendData) GetNameDisplayType() string {
	if x != nil {
		return x.NameDisplayType
	}
	return ""
}

func (x *BasicFriendData) GetAvatarURL() string {
	if x != nil {
		return x.AvatarURL
	}
	return ""
}

type GetFriendListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId string `protobuf:"bytes,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
}

func (x *GetFriendListRequest) Reset() {
	*x = GetFriendListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_friend_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFriendListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendListRequest) ProtoMessage() {}

func (x *GetFriendListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_friend_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendListRequest.ProtoReflect.Descriptor instead.
func (*GetFriendListRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_friend_proto_rawDescGZIP(), []int{1}
}

func (x *GetFriendListRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetFriendListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Friends   []*BasicFriendData `protobuf:"bytes,1,rep,name=friends,proto3" json:"friends,omitempty"`
	Error     string             `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	ErrorCode string             `protobuf:"bytes,3,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
}

func (x *GetFriendListResponse) Reset() {
	*x = GetFriendListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_friend_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFriendListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendListResponse) ProtoMessage() {}

func (x *GetFriendListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_friend_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendListResponse.ProtoReflect.Descriptor instead.
func (*GetFriendListResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_friend_proto_rawDescGZIP(), []int{2}
}

func (x *GetFriendListResponse) GetFriends() []*BasicFriendData {
	if x != nil {
		return x.Friends
	}
	return nil
}

func (x *GetFriendListResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetFriendListResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

type SendFriendListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstAccountId  string `protobuf:"bytes,1,opt,name=firstAccountId,proto3" json:"firstAccountId,omitempty"`
	SecondAccountId string `protobuf:"bytes,2,opt,name=secondAccountId,proto3" json:"secondAccountId,omitempty"`
}

func (x *SendFriendListRequest) Reset() {
	*x = SendFriendListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_friend_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendFriendListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendListRequest) ProtoMessage() {}

func (x *SendFriendListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_friend_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendListRequest.ProtoReflect.Descriptor instead.
func (*SendFriendListRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_friend_proto_rawDescGZIP(), []int{3}
}

func (x *SendFriendListRequest) GetFirstAccountId() string {
	if x != nil {
		return x.FirstAccountId
	}
	return ""
}

func (x *SendFriendListRequest) GetSecondAccountId() string {
	if x != nil {
		return x.SecondAccountId
	}
	return ""
}

type SendFriendListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error     string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	ErrorCode string `protobuf:"bytes,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
}

func (x *SendFriendListResponse) Reset() {
	*x = SendFriendListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_friend_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendFriendListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendListResponse) ProtoMessage() {}

func (x *SendFriendListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_friend_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendListResponse.ProtoReflect.Descriptor instead.
func (*SendFriendListResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_friend_proto_rawDescGZIP(), []int{4}
}

func (x *SendFriendListResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SendFriendListResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

type FriendRequestActionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReceiverId string `protobuf:"bytes,1,opt,name=receiverId,proto3" json:"receiverId,omitempty"`
	RequestId  string `protobuf:"bytes,2,opt,name=requestId,proto3" json:"requestId,omitempty"`
	Action     string `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
}

func (x *FriendRequestActionRequest) Reset() {
	*x = FriendRequestActionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_friend_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendRequestActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequestActionRequest) ProtoMessage() {}

func (x *FriendRequestActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_friend_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequestActionRequest.ProtoReflect.Descriptor instead.
func (*FriendRequestActionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_friend_proto_rawDescGZIP(), []int{5}
}

func (x *FriendRequestActionRequest) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *FriendRequestActionRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FriendRequestActionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type FriendRequestActionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error     string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	ErrorCode string `protobuf:"bytes,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
}

func (x *FriendRequestActionResponse) Reset() {
	*x = FriendRequestActionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_friend_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendRequestActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequestActionResponse) ProtoMessage() {}

func (x *FriendRequestActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_friend_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequestActionResponse.ProtoReflect.Descriptor instead.
func (*FriendRequestActionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_friend_proto_rawDescGZIP(), []int{6}
}

func (x *FriendRequestActionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *FriendRequestActionResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

type FriendRequestRecallRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SenderId  string `protobuf:"bytes,1,opt,name=senderId,proto3" json:"senderId,omitempty"`
	RequestId string `protobuf:"bytes,2,opt,name=requestId,proto3" json:"requestId,omitempty"`
}

func (x *FriendRequestRecallRequest) Reset() {
	*x = FriendRequestRecallRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_friend_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendRequestRecallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequestRecallRequest) ProtoMessage() {}

func (x *FriendRequestRecallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_friend_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequestRecallRequest.ProtoReflect.Descriptor instead.
func (*FriendRequestRecallRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_friend_proto_rawDescGZIP(), []int{7}
}

func (x *FriendRequestRecallRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *FriendRequestRecallRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type FriendRequestRecallResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error     string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	ErrorCode string `protobuf:"bytes,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
}

func (x *FriendRequestRecallResponse) Reset() {
	*x = FriendRequestRecallResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_friend_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendRequestRecallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequestRecallResponse) ProtoMessage() {}

func (x *FriendRequestRecallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_friend_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequestRecallResponse.ProtoReflect.Descriptor instead.
func (*FriendRequestRecallResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_friend_proto_rawDescGZIP(), []int{8}
}

func (x *FriendRequestRecallResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *FriendRequestRecallResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

type FriendFollowRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromAccountId string `protobuf:"bytes,1,opt,name=fromAccountId,proto3" json:"fromAccountId,omitempty"`
	ToAccountId   string `protobuf:"bytes,2,opt,name=toAccountId,proto3" json:"toAccountId,omitempty"`
	Action        string `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
}

func (x *FriendFollowRequest) Reset() {
	*x = FriendFollowRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_friend_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendFollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendFollowRequest) ProtoMessage() {}

func (x *FriendFollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_friend_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendFollowRequest.ProtoReflect.Descriptor instead.
func (*FriendFollowRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_friend_proto_rawDescGZIP(), []int{9}
}

func (x *FriendFollowRequest) GetFromAccountId() string {
	if x != nil {
		return x.FromAccountId
	}
	return ""
}

func (x *FriendFollowRequest) GetToAccountId() string {
	if x != nil {
		return x.ToAccountId
	}
	return ""
}

func (x *FriendFollowRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type FriendFollowResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error     string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	ErrorCode string `protobuf:"bytes,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
}

func (x *FriendFollowResponse) Reset() {
	*x = FriendFollowResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_friend_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendFollowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendFollowResponse) ProtoMessage() {}

func (x *FriendFollowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_friend_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendFollowResponse.ProtoReflect.Descriptor instead.
func (*FriendFollowResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_friend_proto_rawDescGZIP(), []int{10}
}

func (x *FriendFollowResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *FriendFollowResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

type FriendBlockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstAccountId  string `protobuf:"bytes,1,opt,name=firstAccountId,proto3" json:"firstAccountId,omitempty"`
	SecondAccountId string `protobuf:"bytes,2,opt,name=secondAccountId,proto3" json:"secondAccountId,omitempty"`
	Action          string `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
}

func (x *FriendBlockRequest) Reset() {
	*x = FriendBlockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_friend_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendBlockRequest) ProtoMessage() {}

func (x *FriendBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_friend_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendBlockRequest.ProtoReflect.Descriptor instead.
func (*FriendBlockRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_friend_proto_rawDescGZIP(), []int{11}
}

func (x *FriendBlockRequest) GetFirstAccountId() string {
	if x != nil {
		return x.FirstAccountId
	}
	return ""
}

func (x *FriendBlockRequest) GetSecondAccountId() string {
	if x != nil {
		return x.SecondAccountId
	}
	return ""
}

func (x *FriendBlockRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type FriendBlockResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error     string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	ErrorCode string `protobuf:"bytes,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
}

func (x *FriendBlockResponse) Reset() {
	*x = FriendBlockResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_friend_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendBlockResponse) ProtoMessage() {}

func (x *FriendBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_friend_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendBlockResponse.ProtoReflect.Descriptor instead.
func (*FriendBlockResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_friend_proto_rawDescGZIP(), []int{12}
}

func (x *FriendBlockResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *FriendBlockResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

var File_api_proto_friend_proto protoreflect.FileDescriptor

var file_api_proto_friend_proto_rawDesc = []byte{
	0x0a, 0x16, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x22, 0xb1, 0x01, 0x0a, 0x0f, 0x42, 0x61, 0x73, 0x69, 0x63, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x0f,
	0x6e, 0x61, 0x6d, 0x65, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x6e, 0x61, 0x6d, 0x65, 0x44, 0x69, 0x73, 0x70, 0x6c,
	0x61, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72,
	0x55, 0x52, 0x4c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x76, 0x61, 0x74, 0x61,
	0x72, 0x55, 0x52, 0x4c, 0x22, 0x34, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x7e, 0x0a, 0x15, 0x47, 0x65,
	0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x07, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x2e, 0x42, 0x61,
	0x73, 0x69, 0x63, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x61, 0x52, 0x07, 0x66,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1c, 0x0a, 0x09,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x69, 0x0a, 0x15, 0x53, 0x65,
	0x6e, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x66, 0x69, 0x72, 0x73, 0x74, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x66, 0x69, 0x72,
	0x73, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x73,
	0x65, 0x63, 0x6f, 0x6e, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x4c, 0x0a, 0x16, 0x53, 0x65, 0x6e, 0x64, 0x46, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x22, 0x72, 0x0a, 0x1a, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x51, 0x0a, 0x1b, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1c, 0x0a, 0x09,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x56, 0x0a, 0x1a, 0x46, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x63, 0x61, 0x6c,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x49, 0x64, 0x22, 0x51, 0x0a, 0x1b, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x52, 0x65, 0x63, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x75, 0x0a, 0x13, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x46,
	0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0d,
	0x66, 0x72, 0x6f, 0x6d, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x66, 0x72, 0x6f, 0x6d, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x6f, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x6f, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4a, 0x0a, 0x14,
	0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x7e, 0x0a, 0x12, 0x46, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26,
	0x0a, 0x0e, 0x66, 0x69, 0x72, 0x73, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x66, 0x69, 0x72, 0x73, 0x74, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x49, 0x0a, 0x13, 0x46, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x2a, 0x3c, 0x0a, 0x0f, 0x4e, 0x61, 0x6d, 0x65, 0x44, 0x69, 0x73, 0x70, 0x6c,
	0x61, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x46, 0x49, 0x52, 0x53, 0x54, 0x5f,
	0x4e, 0x41, 0x4d, 0x45, 0x5f, 0x46, 0x49, 0x52, 0x53, 0x54, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f,
	0x4c, 0x41, 0x53, 0x54, 0x5f, 0x4e, 0x41, 0x4d, 0x45, 0x5f, 0x46, 0x49, 0x52, 0x53, 0x54, 0x10,
	0x01, 0x32, 0x8f, 0x04, 0x0a, 0x0d, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x53, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x12, 0x1c, 0x2e, 0x66, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x66, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x0e, 0x53, 0x65, 0x6e, 0x64,
	0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1d, 0x2e, 0x66, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x66, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x65, 0x0a, 0x1a, 0x52, 0x65, 0x73,
	0x6f, 0x6c, 0x76, 0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x2e, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x66, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x5e, 0x0a, 0x13, 0x52, 0x65, 0x63, 0x61, 0x6c, 0x6c, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x2e, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65,
	0x63, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x66, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x52, 0x65, 0x63, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x49, 0x0a, 0x0c, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x12, 0x1b, 0x2e, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e,
	0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x46, 0x6f, 0x6c,
	0x6c, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x0b, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x12, 0x1a, 0x2e, 0x66, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x2e,
	0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_friend_proto_rawDescOnce sync.Once
	file_api_proto_friend_proto_rawDescData = file_api_proto_friend_proto_rawDesc
)

func file_api_proto_friend_proto_rawDescGZIP() []byte {
	file_api_proto_friend_proto_rawDescOnce.Do(func() {
		file_api_proto_friend_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_friend_proto_rawDescData)
	})
	return file_api_proto_friend_proto_rawDescData
}

var file_api_proto_friend_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_friend_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_proto_friend_proto_goTypes = []any{
	(NameDisplayType)(0),                // 0: friend.NameDisplayType
	(*BasicFriendData)(nil),             // 1: friend.BasicFriendData
	(*GetFriendListRequest)(nil),        // 2: friend.GetFriendListRequest
	(*GetFriendListResponse)(nil),       // 3: friend.GetFriendListResponse
	(*SendFriendListRequest)(nil),       // 4: friend.SendFriendListRequest
	(*SendFriendListResponse)(nil),      // 5: friend.SendFriendListResponse
	(*FriendRequestActionRequest)(nil),  // 6: friend.FriendRequestActionRequest
	(*FriendRequestActionResponse)(nil), // 7: friend.FriendRequestActionResponse
	(*FriendRequestRecallRequest)(nil),  // 8: friend.FriendRequestRecallRequest
	(*FriendRequestRecallResponse)(nil), // 9: friend.FriendRequestRecallResponse
	(*FriendFollowRequest)(nil),         // 10: friend.FriendFollowRequest
	(*FriendFollowResponse)(nil),        // 11: friend.FriendFollowResponse
	(*FriendBlockRequest)(nil),          // 12: friend.FriendBlockRequest
	(*FriendBlockResponse)(nil),         // 13: friend.FriendBlockResponse
}
var file_api_proto_friend_proto_depIdxs = []int32{
	1,  // 0: friend.GetFriendListResponse.friends:type_name -> friend.BasicFriendData
	2,  // 1: friend.FriendService.GetAccountListFriend:input_type -> friend.GetFriendListRequest
	4,  // 2: friend.FriendService.SendFriendList:input_type -> friend.SendFriendListRequest
	6,  // 3: friend.FriendService.ResolveFriendRequestAction:input_type -> friend.FriendRequestActionRequest
	8,  // 4: friend.FriendService.RecallFriendRequest:input_type -> friend.FriendRequestRecallRequest
	10, // 5: friend.FriendService.FollowFriend:input_type -> friend.FriendFollowRequest
	12, // 6: friend.FriendService.BlockFriend:input_type -> friend.FriendBlockRequest
	3,  // 7: friend.FriendService.GetAccountListFriend:output_type -> friend.GetFriendListResponse
	5,  // 8: friend.FriendService.SendFriendList:output_type -> friend.SendFriendListResponse
	7,  // 9: friend.FriendService.ResolveFriendRequestAction:output_type -> friend.FriendRequestActionResponse
	9,  // 10: friend.FriendService.RecallFriendRequest:output_type -> friend.FriendRequestRecallResponse
	11, // 11: friend.FriendService.FollowFriend:output_type -> friend.FriendFollowResponse
	13, // 12: friend.FriendService.BlockFriend:output_type -> friend.FriendBlockResponse
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_friend_proto_init() }
func file_api_proto_friend_proto_init() {
	if File_api_proto_friend_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_friend_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*BasicFriendData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_friend_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetFriendListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_friend_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetFriendListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_friend_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*SendFriendListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_friend_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*SendFriendListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_friend_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*FriendRequestActionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_friend_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*FriendRequestActionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_friend_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*FriendRequestRecallRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_friend_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*FriendRequestRecallResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_friend_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*FriendFollowRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_friend_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*FriendFollowResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_friend_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*FriendBlockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_friend_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*FriendBlockResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_friend_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_friend_proto_goTypes,
		DependencyIndexes: file_api_proto_friend_proto_depIdxs,
		EnumInfos:         file_api_proto_friend_proto_enumTypes,
		MessageInfos:      file_api_proto_friend_proto_msgTypes,
	}.Build()
	File_api_proto_friend_proto = out.File
	file_api_proto_friend_proto_rawDesc = nil
	file_api_proto_friend_proto_goTypes = nil
	file_api_proto_friend_proto_depIdxs = nil
}
